Consolidate windows builds into one file
coin-or/CoinUtils pull request #169
Opened 2021-05-16 18:15 UTC by xmunoz

2021-05-17 19:54 UTC, tkralphs requested changes

2021-05-17 19:54 UTC, tkralphs commented on .github/workflows/windows-ci.yml
> +          [[ ${{ matrix.debug }} == "false" ]] && debug="" tests="none" || debug="--enable-debug" tests="main"
What we had before was `--tests main` when `debug` is `false` and `--tests none` when `debug` is true, but I think that was only to speed things up on Appveyor and I would be happy for now if we just do the testing in all cases.

2021-05-18 02:50 UTC, tkralphs reviewed
I just noticed that we aren't uploading the build artifacts for the Windows builds, but we are for the Linux and OS X builds. Can we also do that? If the build artifacts could be uploaded for every build, that would actually fully replicate what we were doing with Bintray, but in a much nicer way. Is there any reason not to do that?

2021-05-18 15:18 UTC, xmunoz commented
https://github.com/coin-or/CoinUtils/actions/runs/851243177

If you scroll down, you'll see the artifacts. Let's review any other concerns you have on our call.

2021-05-18 21:39 UTC, merged